### ISSUE TITLE
vnicppcodegen throws segfault when called without parameters

### ISSUE THREAD

**Issue by m4nue1X** [madMAx43v3r/virtual-network-interface#2]
gdb output:

```
Program received signal SIGSEGV, Segmentation fault.
0x000556d0 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> > >::_M_begin (this=0x38) at /usr/include/c++/6.1.1/bits/stl_tree.h:662
662           { return static_cast<_Link_type>(this->_M_impl._M_header._M_parent); }
```

backtrace:

```
#0  0x000556d0 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> > >::_M_begin (this=0x38) at /usr/include/c++/6.1.1/bits/stl_tree.h:662
#1  0x00059cd8 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> > >::lower_bound (this=0x38, __k="vnl.Value") at /usr/include/c++/6.1.1/bits/stl_tree.h:1098
#2  0x00055708 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, vni::codegen::Base*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> > >::lower_bound (this=0x38, __x="vnl.Value") at /usr/include/c++/6.1.1/bits/stl_map.h:1150
#3  0x00051b90 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, vni::codegen::Base*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, vni::codegen::Base*> > >::operator[] (this=0x38, __k="vnl.Value") at /usr/include/c++/6.1.1/bits/stl_map.h:479              
#4  0x000420f4 in vni::codegen::resolve<vni::codegen::Base> (ident="vnl.Value") at /home/alarm/virtual-network-interface/codegen/cpp/../AST.h:326                                                                               
#5  0x00040a8c in vni::codegen::resolve (ident="vnl.Value") at /home/alarm/virtual-network-interface/codegen/cpp/../AST.h:337                                                                                                        
#6  0x00059778 in vni::codegen::Compiler<vni::codegen::VNIParser>::register_default (this=0x7efffaec) at /home/alarm/virtual-network-interface/codegen/cpp/../Compiler.h:52                                                              
#7  0x00055224 in vni::codegen::Compiler<vni::codegen::VNIParser>::compile (this=0x7efffaec) at /home/alarm/virtual-network-interface/codegen/cpp/../Compiler.h:31                                                                       
#8  0x00041fbc in main (argc=1, argv=0x7efffc84) at /home/alarm/virtual-network-interface/codegen/cpp/vnicppcodegen.cpp:27
```

**Comment by madMAx43v3r** [comment]
Yep forgot the exit(-1). Thanks.
